config/routes.rb
Platform::Application.routes.draw do
  
  get "maps/index"

  get "plot/index"

  get "simulation/index"
  post "simulation/index"
  get "hosts/new"
  get "sessions/new"
  get "simulation/upload"
  post "simulation/upload"
  get "simulation/download"
  post "simulation/download"
  get "simulation/download_template"
  post "simulation/download_result"

  
  resources :users do
    member do 
      post 'auth'
    end
    
  end
  resources :sessions, :only => [:new, :create, :destroy ]

  
  match '/help',      :to => 'pages#help'
  match '/contact',   :to => 'pages#contact'
  match '/about',     :to => 'pages#about'
  match '/signin' ,   :to => 'sessions#new'
  match '/signout',   :to => 'sessions#destroy'
  match '/signup' ,   :to => 'users#new'
  match '/simulation',:to => 'simulation#index'
  match '/status',    :to => 'pages#status'
  match '/lookup',    :to => 'simulation#lookup'
  match '/plot',      :to => 'plot#index', :as => :plot
  match '/map',       :to => 'maps#index',:as => :map
  root :to => 'pages#input'

end

app/models/user.rb
# encoding: utf-8
class User < ActiveRecord::Base
  attr_accessible :name, :email, :password, :password_confirmation
  has_secure_password
  
  validates :name, :presence => true,
                   :uniqueness => { :case_sensitive => false },
                   :length => { :maximum => 20 }

  email_regex = /\A[\w+\-.]+@zte\.com\.cn/i
  validates :email, :presence => true,
                    :uniqueness => { :case_sensitive => false },
                    :format => {:with => email_regex, :message => '用中兴邮箱注册'}

 
  validates :password, :on => :create, 
                       :confirmation => true,
                       :presence => true,
                       :length => {:within => 6..20,           
                        :too_short => "密码必须大于%{count}位数",
                        :too_long => "密码必须小于%{count}位"}
  validates :password_confirmation, :presence => true


#  validates password_digest
end

app/controllers/application_controller.rb
# -*- coding: utf-8 -*-
class ApplicationController < ActionController::Base
  protect_from_forgery

  def redirect_back_or(default)
    redirect_to(session[:return_to] || default)
    clear_return_to
  end

  
private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def current_user=(user)
    @current_user = user
  end
  def current_user?(user)
    user == current_user
  end

    def store_location
      session[:return_to] = request.fullpath
    end

    def clear_return_to
      session[:return_to] = nil
    end

    #如果文件名有空格，可能造成识别服务器识别不正确，需要函数来去掉
    def getfilename(filename)
      if !filename.nil?
        filename.split(' ').to_s
      end
    end
  helper_method :current_user, :current_user?,:redirect_back_or,
         :store_location, :clear_return_to, :getfilename
end

app/controllers/maps_controller.rb
class MapsController < ApplicationController
  def index
  end
end

app/controllers/pages_controller.rb
# encoding: utf-8
class PagesController < ApplicationController
  def input
    @title = "首页"
  end

  def help
    @title = "帮助"
  end

  def contact
    @title = "联系我"
  end

  def about
    @title = "关于"
  end

  def status
    @title = '集群负载状态'
  end
end

app/controllers/plot_controller.rb
ffclass PlotController < ApplicationController
  def index
  end
end

app/controllers/sessions_controller.rb
# encoding: utf-8
class SessionsController < ApplicationController

  def new
    @title = "sign in"
  end

  def create
    user = User.find_by_email(params[:session][:email])
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
#      redirect_to user_url(user), :notice => "你已经登录!"
      redirect_back_or user
      flash[:success] = "你已经登录!"
    else
      flash.now.alert = "邮件地址或密码错误"
      @title = 'Sign in'
      render "new"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, :notice => "已经注销!"
  end
end

app/controllers/simulation_controller.rb
# -*- coding: utf-8 -*-
class SimulationController < ApplicationController

  def index
    @title = '仿真主页'
  end

  def upload
    require 'fileutils'
    @user_name = current_user.name
    @job_name = params[:job_name]

    @name = params[:file].original_filename
    @directory = Rails.root.join('app/assets/data').join(@user_name).join(@job_name)
    FileUtils.mkdir_p(@directory)  unless File.directory?(@directory)
    @path = File.join(@directory,@name) 
    @result = File.open(@path,'wb') {|f| f.write(params[:file].read)}
    @cluster_selected = params[:cluster]
  end

  def download
    require 'fileutils'
    @user_name = current_user.name
    @job_name = params[:job_name]
    @cluster_selected = params[:cluster]
    @resultPath = Rails.root.join('app/assets/result')

    flash[:success] = @job_name
  end
  
  def download_result
    @job_name = flash[:success]
    @resultPath = Rails.root.join('app/assets/result')
    FileUtils.mkdir_p(@resultPath)  unless File.directory?(@resultPath)
    @resultFile = Rails.root.join('app').join('assets').join('result').join('result.mat')
    File.open(@resultFile, 'rb') do |f| 
      send_data f.read, :disposition => "inline",
      :stream => false,
      :filename => "#{@job_name}.mat"
    end 
    FileUtils.rm @resultFile
  end
  
  def download_template
     @excel_path = Rails.root.join('app').join('assets').join('data')
     @excel_file_name = 'ParameterTable.xls'
     @excel_locate = File.join(@excel_path,@excel_file_name)
     File.open(@excel_locate, 'rb') do |f| 
       send_data f.read, :disposition => "inline",:stream => false,:filename => 'ParameterTable.xls'
    end
  end
end

app/controllers/users_controller.rb
# encoding: utf-8
class UsersController < ApplicationController
  before_filter :authenticate, :only => [:edit, :update, :index]
  before_filter :correct_user, :only => [:edit, :update]
  before_filter :admin_user,   :only => :destroy

  def index
    @title = "All users"
    @users = User.all
  end

  def new
    @user = User.new
    @title = "sign up"
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      flash[:success] = "欢迎注册，请等待管理员授权"
      current_user= @user
      session[:user_id] = @user.id
      redirect_to @user
    else
      @title = 'Sign up'
      render "new"
    end
  end

  def show
    @user = User.find(params[:id])
    @title = @user.name
  end

  def edit
    @user = User.find(params[:id])
    @title = "Edit user"
  end
   
  def update
    @user = User.find(params[:id])
    if @user.update_attributes(params[:user])
      flash[:success] = "资料已更新."
      redirect_to @user
    else
      @title = "Edit user"
      render 'edit'
    end
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "用户已删除"
    redirect_to users_path
  end

  def auth
    User.find(params[:id]).toggle!(:auth)
    flash[:success] = "用户已授权"
    redirect_to users_path    
  end


  private

    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_path) unless current_user?(@user)
    end
    
    def authenticate
      deny_access if current_user.nil?
    end
    
    def admin_user
      redirect_to(root_path) unless current_user.admin?
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def title
    base_title = "System Simulation Department"
    if @title.nil?
      base_title
    else
      "#{base_title}| #{@title}"
    end
  end
  def logo
    image_tag("ssd.png", :alt => "Simulation", :class => "round")
  end

end

app/helpers/maps_helper.rb
module MapsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/plot_helper.rb
module PlotHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def deny_access
    redirect_to signin_path, :notice => "Please sign in to access this page."
  end


  private

 end

app/helpers/simulation_helper.rb
module SimulationHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(user, options = { :size => 50 })
    gravatar_image_tag(user.email.downcase, :alt => user.name,
                                            :class => 'gravatar',
                                            :gravatar => options)
  end

  def remove_sensitive_error_messages_from_user(user)
    @user.errors.full_messages.delete_if { |msg| msg =~ /digest/ }
  end
end

app/views/layouts/_footer.html.haml
%li.navi-font
  = link_to about_path do
    %i.icon-book
    About
%li.navi-font 
  = link_to contact_path do
    %i.icon-envelope
    Contact
%li.navi-font
  = link_to  help_path do
    %i.icon-question-sign
    Help



app/views/layouts/_head.html.haml
%meta{:charset => 'utf-8'}
%meta{:name => 'viewport',:content => 'width=device-width'}
%title 
  = title
= render "layouts/javascripts" 
= csrf_meta_tags 
= render "layouts/stylesheets" 

app/views/layouts/_header.html.haml
%ul.nav.nav-list
  %li.nav-header
    Main Menu
  %li.navi-font
    = link_to root_path do
      %i.icon-home
      Home
  %li.navi-font
    - if current_user.nil?
      = link_to signin_path do
        %i.icon-user
        Sign in
  - if !current_user.nil?
    %li.divider
    %li.nav-header.navi-font
      User Menu
  %li.navi-font
    - if !current_user.nil?
      = link_to  signout_path, :method => :delete do
        %i.icon-off
        Logout
  %li.navi-font
    - if !current_user.nil?
      = link_to edit_user_path(current_user)  do
        %i.icon-cog
        Setting
  %li.navi-font
    - if !current_user.nil?
      = link_to current_user do
        %i.icon-info-sign
        Profile
  %li.navi-font
    - if !current_user.nil?
      = link_to users_path do
        %i.icon-list
        Users
  - if !current_user.nil?
    %li.divider
    %li.nav-header.navi-font
      Simu Menu
  %li.navi-font
    - if !current_user.nil?
      = link_to status_path do
        %i.icon-adjust
        Status  
  %li.navi-font
    - if !current_user.nil?
      = link_to lookup_path do
        %i.icon-search
        Lookup          
  %li.navi-font
    - if !current_user.nil?
      = link_to simulation_path do
        %i.icon-signal
        Simulation
  %li.navi-font
    - if !current_user.nil?
      = link_to plot_path do
        %i.icon-edit
        Plot
  %li.navi-font
    - if !current_user.nil?
      = link_to map_path do
        %i.icon-road
        Parameter
  %li.divider
  %li.nav-header.navi-font
    Info Menu
  = render 'layouts/footer'

app/views/layouts/_javascripts.html.haml
/[if lt IE 9]
  %script{ "src" => "http://html5shim.googlecode.com/svn/trunk/html5.js","type"=>"text/javascript"}
= javascript_include_tag "application"
= yield :maps
= yield :plot

app/views/layouts/_stylesheets.html.haml
= stylesheet_link_tag "application" 

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    = render 'layouts/head'
  %body
    #header
      .row-fluid
        .span2
          %i
            = link_to logo, root_path
        .span8
          %h1
            System Simulation Department
    .container-fluid
      .row-fluid#body
        .span2#nav
          = render 'layouts/header'
        .span6
          - flash.each do |key, value|
            %div{:class => "alert alert-#{key}"} 
              = value
          .row-fluid
            .hero-unit
              = yield
    %footer
      %section
        #footer
      %section.debug
        %hr/
        .alert.alert-block

app/views/maps/index.html.haml
= content_for :maps do 
  %script{ "src" => "http://maps.google.com/maps/api/js?sensor=true","type"=>"text/javascript"}
  = javascript_include_tag 'maps'
#maps

app/views/pages/about.html.haml
%legend
  %h1
    .inner-title
      About the Platform 
%br/
%p  
  The Simulation System belongs to System Simulation Department of ZTE ... 

app/views/pages/contact.html.haml
%legend
  %h1
    .inner-title
      Contact Information 
%br/
%p 
  Any usage problem please feel comfortable to contact me 
  = mail_to  "zhang.qingbo@zte.com.cn", "Mail Me", :class => "btn btn-large btn-primary"

app/views/pages/help.html.haml
%legend
  %h1
    .inner-title
      Help
%br/	  
%p
  Help Info need to be completed!

app/views/pages/input.html.haml
%legend
  %h1
    .inner-title
      ZTE System Simulation Platform
%br/
%p
  This is the home page for the Using and Management of ZTE Wireless System Simulation Platform
  = link_to "click here to get more information", about_path
%br/
.row-fluid
  - if current_user.nil?
    #sign-up-button
      = link_to "Sign up now!", signup_path,:id => 'button-color'        
      

app/views/pages/status.html.haml
%legend
  %h1
    .inner-title
      Jobmanager Status
%br/
= render 'shared/status'

app/views/plot/index.html.haml
= content_for :plot do 
  = javascript_include_tag 'plot'
#container-plot

app/views/shared/_error_messages.html.haml
- if object.errors.any?
  #error_explanation.alert.alert-error
    /%h3
    /  = pluralize(object.errors.count, "error")
    /  prohibited this
    /  = object.class.to_s.underscore.humanize.downcase
    /  from being saved
    %p
      下面这几栏目有问题请检查：
    %ul
      - object.errors.full_messages.each do |msg| 
        %li
          = msg
- remove_sensitive_error_messages_from_user(@user)

app/views/shared/_status.html.haml
%ul
  %table.table.table-striped.table-bordered.table-condensed
    %tr
      %th
        JobManagerName
      %th
        Current Load (%)
      %tr
        %td
          %i.icon-time
          jm-c
        %td 
          %i.icon-eye-open
          0
      %tr
        %td
          %i.icon-time
          jm-u
        %td 
          %i.icon-eye-open
          0

app/views/simulation/download.html.haml
%legend
  %h1
    .inner-title
      Look up result
%br/
- if @result_judge == true 
  = form_tag('download_result',:class =>'form-horizontal') do
    .control-group
      %label.control-label
        your job name
      .controls
        ="#{@job_name}" 
    .control-group
      %label.control-label
        Download result
      .controls
        = submit_tag "Download",:class =>'btn btn-primary'
- else 
  %h2
    There is No Job finished In 
    .control-group
      %label.control-label
        User Name:
      .controls
        = "  #{@user_name}"
    .control-group
      %label.control-label
        Job Name:
      .controls
        = "  #{@job_name}"


app/views/simulation/index.html.haml
%legend
  %h1
    .inner-title
      Collection data  trigger Simulation
%hr/
%h3
  = link_to "download excel", :action => "download_template" 
%hr/
= form_tag("simulation/upload", :multipart => true, :class =>'form-horizontal') do 
  %fieldset
    %h3
      Simulation
    .control-group
      %label.control-label
        Current Load
      .controls
        = render 'shared/status'
    .control-group
      %label.control-label
        Choose a cluster
      .controls
        = radio_button_tag('cluster', 'jm_c', checked = true)
        JM-C cluster
        = radio_button_tag('cluster', 'jm_u', checked = false)
        JM-U cluster
    .control-group
      %label.control-label
        Input Your unique job name
      .controls
        = text_field_tag 'job_name'
    .control-group
      %label.control-label
        Choose file on local disk
      .controls
        = file_field_tag "file"
    .control-group
      %label.control-label
        click wait and be patient!
      .controls
        = submit_tag "Submit file lanuch simulation",:class =>'btn btn-primary'

app/views/simulation/lookup.html.haml
%legend
  %h1
    .inner-title
      Look up Your job result
%br/
= form_tag('simulation/download',:class =>'form-horizontal') do 
  .control-group
    %label.control-label      	
      Job Name
    .controls
      = text_field_tag 'job_name'
  .control-group
    %label.control-label
      Choose a cluster
    .controls
      = radio_button_tag('cluster', 'jm_c', checked = true)
      JM-C cluster
      = radio_button_tag('cluster', 'jm_u', checked = false)
      JM-U cluster
  .control-group
    %label.control-label
      Goto The Result
    .controls  
      = submit_tag "Go...",:class =>'btn btn-primary'

app/views/simulation/upload.html.haml
%legend
  %h1
    .inner-title
    Your Job Info
%br/
%table.table.table-striped.table-bordered.table-condensed
  %tr
    %th
      JobManager Name
    %th
      User Name
    %th
      Job Name
  %tr
    %td
      = "#{@cluster_selected.to_s.upcase.gsub(/_/,'-')}"
    %td 
      = "#{@user_name}"
    %td 
      = "#{@job_name}"
%br/
%h3
  You can query your submited job result by information listed above
  = link_to 'LookUp', lookup_path

app/views/users/_user.html.haml
%tr
  %td
    = gravatar_for user, :size => 40
  %td
    - if current_user.admin? 
      = link_to user do
        %h4
          %em.pull-left
            = user.name
    - else
      %h4
        %em.pull-left
          = user.name
  - if current_user.admin? 
    %td
      = link_to  "delete", user,
        :confirm => "are you sure?",
        :method => :delete,
        :class => "btn btn-danger"
    - if  user.auth?
      %td
        = link_to "Unauth",auth_user_path(user),	
          :confirm =>"are you sure?",
          :method => :post,
          :class => "btn btn-inverse"
    - else 
      %td
        = link_to "auth",auth_user_path(user),
          :confirm => "are you sure", 
          :method => :post,
          :class => "btn btn-success"
  %td
    - if  user.auth?
      %span.label.label-success
        has Auth
    - else 
      %span.label
        Not Auth

app/views/users/edit.html.haml
= form_for(@user,:html => {:class =>'form-horizontal'}) do |f|
  %fieldset
    %legend
      %h1
        .inner-title
          Edit user
    = render 'shared/error_messages', :object => f.object 
    .control-group
      = f.label :name, :class => 'control-label'
      .controls
        = f.text_field :name,:class => 'input-middle',:placeholder => "New Name"
    .control-group
      = f.label :email,:class => 'control-label'
      .controls
        = f.text_field :email,:class => 'input-middle',:placeholder => "*@zte.com.cn"
    .control-group
      = f.label :password, :class => 'control-label'
      .controls
        = f.password_field :password,:class => 'input-middle',:placeholder => "new password"
    .control-group
      = f.label :password_confirmation,:class =>'control-lable'
      .controls
        = f.password_field :password_confirmation,:class => 'input-middle',:placeholder => "confirm new password"
    .control-group
      %label.control-label
        Update Properties
      .controls
        = f.submit "Update", :class =>'btn btn-primary'
    %hr/            
    .control-group
      %label.control-label
        change your avatar
      .controls
        = link_to gravatar_for(@user), "http://gravatar.com/emails"

app/views/users/index.html.haml
%h1
  .inner-title
    All users Listed Here
%br/
%table.table.table-striped.table-bordered.table-condensed
  %thead
    %tr
      %th 
        %h3
          %strong
            Photo
      %th
        %h3
          %strong
            Name
      - if current_user.admin? 
        %th
          %h3
            %strong
              Delete
        %th
          %h3
            %strong
              Authenticate
      %th
        %h3
          %strong
            Status
  %tbody
    = render @users

app/views/users/new.html.haml
= form_for(@user,:html => {:class =>'form-horizontal'}) do |f|
  %fieldset
    %legend
      %h1
        .inner-title
          Sign up and wait for Authorization
    = render 'shared/error_messages', :object => f.object
    .control-group
      = f.label :name,:class => 'control-label'
      .controls
        = f.text_field :name,:class => "input-middle",:placeholder => "Your name to display"
    .control-group
      = f.label :email,:class => 'control-label'
      .controls
        = f.text_field :email,:class => "input-middle",:placeholder => "***@zte.com.cn"
    .control-group
      = f.label :password,:class => 'control-label'
      .controls
        = f.password_field :password,:class => "input-middle",:placeholder => "********"
    .control-group
      = f.label :password_confirmation,:class => 'control-label'
      .controls
        = f.password_field :password_confirmation,:class => "input-middle",:placeholder => "********"
    .control-group
      %label.control-label
        Sign Up
      .controls
        = f.submit "SignUp", :class =>'btn btn-primary'

app/views/users/show.html.haml
%legend
  %h1
    .inner-title
      Profile information
.row-fluid
  .span8
    %table.table.table-striped.table-bordered.table-condensed
      %thead
        %tr
          %th
            %h3
              %strong
                Name
          %td
            %h3
              %em
                = @user.name   
        %tr
          %th
            %h3
              %strong
                Email
          %td
            %h3
              %em
                = link_to @user.email, @user 
        %tr
          %th
            %h3
              %strong
                Other
          %td
            %h3
              %em
                /....                       
  .span4
    = gravatar_for(@user,:size => 105)  
        